heat_template_version: 2013-05-23

description: >
  Created 4/28/16 by ucdpadmin. For Cloud patterns-service-dev@riddler

parameters:
  flavor:
    type: string
    description: Flavor to be used for compute instance
  key_name:
    type: string
    description: For most clouds, the name of the key-pair to be used for the compute instance; for VMware clouds, the contents of the public SSH key for the compute instance
  availability_zone:
    type: string
    description: Name of availability zone in which to create the instance
    default: 'nova'
  network-id__for__patterns-service-dev-net:
    type: string
    description: Generated to reference 'patterns-service-dev-net' network.
    default: 'fbd19302-f247-4816-b53e-a664f3dc72c1'
  name:
    type: string
    description: Generated
    default: 'CentOS-6-x86_64-20150911'
  image:
    type: string
    description: CentOS-6-x86_64-20150911
    default: 'e3586645-c7ff-4deb-b79f-f2db308cb1bd'
  java7_enabled:
    type: boolean
    description: Select enable java7 or not
    default: true
    constraints:
        - allowed_values: [true,false]
  boolean_type:
    type: boolean
    description: " boolean type"
  number_type:
     type: number
     description: " number type"
     default: 6
     constraints:
         - allowed_values: [6,8,2]

resources:
## REFERENCE {"patterns-service-dev-net":{"type": "OS::Neutron::Net", "properties": {"network_id": "fbd19302-f247-4816-b53e-a664f3dc72c1", "external":"false", "subnets": [{"id":"46fcd6d7-017e-437b-9921-d7fb9f76a7f2","name":"patterns-service-dev-subnet","cidr":"192.168.15.0\/24"}] }}}

  CentOS-6-x86_64-20150911:
    type: OS::Nova::Server
    properties:
      networks:
          - port: { get_resource: CentOS-6-x86_64-20150911__to__patterns-service-dev-net__port  }
      name: { get_param: name }
      image: { get_param: image }  # CentOS-6-x86_64-20150911
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      availability_zone: { get_param: availability_zone }


  CentOS-6-x86_64-20150911__to__patterns-service-dev-net__port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: network-id__for__patterns-service-dev-net }

outputs:
  blueprint_url:
    description: Blueprint Origin URL
    value:  http://localhost:8080/landscaper/view/projects?open=ucdpadmin_00000000_0000_0000_0000_000000000002-OrionContent/default/helloWorld/helloWorld.yml
